services:
  - type: web
    name: test-appointment-website
    runtime: node
    region: frankfurt
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm run seed && npm start"
    healthCheckPath: /api/health
    envVars:
      - key: BUSINESS_NAME
        value: Test Appointment Website
      - key: BUSINESS_EMAIL
        sync: false
      - key: PROVIDER_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: DB_PATH
        value: /data/data.sqlite
      # - key: BASE_URL
      #   value: https://your-app.onrender.com
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
